//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using AssemblyCSharp;
using Unity_Code;

namespace AssemblyCSharp
{
	public class MainPiece
	{

		public ArrayList CodeHeap;


		
		public MainPiece()
		{
			CodeHeap = new ArrayList();

		}

		public void addCode(IProgrammingPiece command)
		{
			CodeHeap.Add(command);


		}

		public void removeCode(IProgrammingPiece command)
		{
			CodeHeap.Remove (command);
		}

		public int Execute()
		{
			foreach (IProgrammingPiece command in CodeHeap) 
			{
				command.Execute();
			}
			return 0;
		}



		
		
		
	}
}

