//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using Unity_Code;

namespace AssemblyCSharp
{
		public static class variablelist
		{
		public Dictionary<char, number> VariableDict;
		
	
		}
}

